version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/bmart-5
permissions:
  - object: /home/ubuntu/bmart-5
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: /home/ubuntu/bmart-5/deploy.sh
      timeout: 60
      runas: ubuntu
