version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/bmart-5
permissions:
  - object: /home/ubuntu/bmart-5
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: ubuntu
